#!/usr/bin/env php
<?php

/*
|--------------------------------------------------------------------------
| Artisan Console Application
|--------------------------------------------------------------------------
|
| This file is the entry point for the Artisan CLI. You do not need to
| modify this file as it will always bootstrap your application using
| the autoloader.
|
*/

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

exit($kernel->handle(new Symfony\Component\Console\Input\ArgvInput, new Symfony\Component\Console\Output\ConsoleOutput));
